-- MySQL Script generated by MySQL Workbench
-- Mon Nov 14 05:00:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mascotillas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mascotillas` ;

-- -----------------------------------------------------
-- Schema mascotillas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mascotillas` DEFAULT CHARACTER SET utf8 ;
USE `mascotillas` ;

-- -----------------------------------------------------
-- Table `mascotillas`.`Ficha-de-Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascotillas`.`Ficha-de-Tienda` (
  `idFichaTienda` INT NOT NULL,
  `fecha` DATETIME NULL,
  `precio` DECIMAL(20) NULL,
  `tipo_mascota` VARCHAR(45) NULL,
  `productos` VARCHAR(45) NULL,
  PRIMARY KEY (`idFichaTienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascotillas`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascotillas`.`Tienda` (
  `idProducto` INT NULL,
  `tipoDeProducto` VARCHAR(80) NULL,
  `Ficha-de-Tienda_idFichaTienda` INT NOT NULL,
  PRIMARY KEY (`idProducto`, `Ficha-de-Tienda_idFichaTienda`),
  CONSTRAINT `fk_Tienda_Ficha-de-Tienda1`
    FOREIGN KEY (`Ficha-de-Tienda_idFichaTienda`)
    REFERENCES `mascotillas`.`Ficha-de-Tienda` (`idFichaTienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tienda_Ficha-de-Tienda1_idx` ON `mascotillas`.`Tienda` (`Ficha-de-Tienda_idFichaTienda` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mascotillas`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascotillas`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `Tienda_idProducto` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Tienda_idProducto`),
  CONSTRAINT `fk_Usuario_Tienda1`
    FOREIGN KEY (`Tienda_idProducto`)
    REFERENCES `mascotillas`.`Tienda` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_Tienda1_idx` ON `mascotillas`.`Usuario` (`Tienda_idProducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mascotillas`.`ficha-de-Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascotillas`.`ficha-de-Servicios` (
  `idfichaDeServicios` INT NOT NULL,
  `fecha` DATE NULL,
  `nombre_dueño` VARCHAR(45) NULL,
  `telefono_dueño` INT NULL,
  `direccion_dueño` VARCHAR(60) NULL,
  `nombre_mascota` VARCHAR(45) NULL,
  `edad_mascota` INT NULL,
  `tipo_mascota` VARCHAR(45) NULL,
  `precio` DECIMAL(20) NULL,
  PRIMARY KEY (`idfichaDeServicios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascotillas`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascotillas`.`Servicios` (
  `idServicios` INT NOT NULL,
  `tipoDeServicio` VARCHAR(45) NULL,
  `precio` DECIMAL(20) NULL,
  `ficha-de-Servicios_idfichaDeServicios` INT NOT NULL,
  PRIMARY KEY (`idServicios`, `ficha-de-Servicios_idfichaDeServicios`),
  CONSTRAINT `fk_Servicios_ficha-de-Servicios1`
    FOREIGN KEY (`ficha-de-Servicios_idfichaDeServicios`)
    REFERENCES `mascotillas`.`ficha-de-Servicios` (`idfichaDeServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Servicios_ficha-de-Servicios1_idx` ON `mascotillas`.`Servicios` (`ficha-de-Servicios_idfichaDeServicios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mascotillas`.`Servicios_has_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascotillas`.`Servicios_has_Usuario` (
  `Usuario_idUsuario` INT NOT NULL,
  `Servicios_idServicios` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Servicios_idServicios`),
  CONSTRAINT `fk_Servicios_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mascotillas`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicios_has_Usuario_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `mascotillas`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Servicios_has_Usuario_Servicios1_idx` ON `mascotillas`.`Servicios_has_Usuario` (`Servicios_idServicios` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mascotillas`.`InfoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascotillas`.`InfoUsuario` (
  `idInfoUsuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(60) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_Tienda_idProducto` INT NOT NULL,
  PRIMARY KEY (`idInfoUsuario`, `Usuario_idUsuario`, `Usuario_Tienda_idProducto`),
  CONSTRAINT `fk_InfoUsuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_Tienda_idProducto`)
    REFERENCES `mascotillas`.`Usuario` (`idUsuario` , `Tienda_idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_InfoUsuario_Usuario1_idx` ON `mascotillas`.`InfoUsuario` (`Usuario_idUsuario` ASC, `Usuario_Tienda_idProducto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mascotillas`.`Adopcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascotillas`.`Adopcion` (
  `idAdopcion` INT NOT NULL,
  `fecha` DATETIME NULL,
  `tamaño` VARCHAR(45) NULL,
  `caracter` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `salud` VARCHAR(45) NULL,
  `requerimientosAdopcion` VARCHAR(120) NULL,
  PRIMARY KEY (`idAdopcion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mascotillas`.`Adopcion_has_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mascotillas`.`Adopcion_has_usuario` (
  `Usuario_idUsuario` INT NOT NULL,
  `Adopcion_idAdopcion` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Adopcion_idAdopcion`),
  CONSTRAINT `fk_Adopcion_has_usuario_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mascotillas`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Adopcion_has_usuario_Adopcion1`
    FOREIGN KEY (`Adopcion_idAdopcion`)
    REFERENCES `mascotillas`.`Adopcion` (`idAdopcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Adopcion_has_usuario_Adopcion1_idx` ON `mascotillas`.`Adopcion_has_usuario` (`Adopcion_idAdopcion` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
